
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MRX
 */
public class Frame1 extends javax.swing.JFrame {
    String temp="";
    Double ti, bt, h1;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        knama = new javax.swing.JTextField();
        ktinggi = new javax.swing.JTextField();
        kberat = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        kideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 30, 110, 20);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 110, 50, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 160, 70, 14);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 210, 80, 14);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 260, 80, 14);

        jLabel6.setText("Berat Badan ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 380, 170, 14);
        getContentPane().add(knama);
        knama.setBounds(250, 100, 240, 30);
        getContentPane().add(ktinggi);
        ktinggi.setBounds(250, 150, 240, 30);

        kberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kberatActionPerformed(evt);
            }
        });
        getContentPane().add(kberat);
        kberat.setBounds(250, 200, 240, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Perempuan");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(240, 250, 110, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Laki - laki");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(380, 250, 110, 23);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(120, 300, 80, 23);

        jButton2.setText("Coba Lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 300, 90, 23);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 300, 80, 23);
        getContentPane().add(kideal);
        kideal.setBounds(300, 370, 190, 30);

        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(233, 430, 150, 14);
        getContentPane().add(hasil);
        hasil.setBounds(140, 470, 350, 30);
        getContentPane().add(saran);
        saran.setBounds(139, 520, 350, 30);

        jLabel8.setText("cm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 160, 50, 20);

        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 210, 50, 20);

        setBounds(0, 0, 638, 664);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        if (knama.getText().equals("") ||ktinggi.getText().equals("")||
                kberat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data inputan harus diisi");
        }else if(jRadioButton1.isSelected()||jRadioButton2.isSelected()){
            try{
                Proses();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data inputan salah");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Jenis Kelamin belum dipilih");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void kberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kberatActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        knama.setText("");
        ktinggi.setText("");
        kberat.setText("");
        kideal.setText("");
        hasil.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField kberat;
    private javax.swing.JTextField kideal;
    private javax.swing.JTextField knama;
    private javax.swing.JTextField ktinggi;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(ktinggi.getText());
        bt = Double.valueOf(kberat.getText());
        
        if(jRadioButton1.isSelected()){
            h1 = (ti - 100) * 1;
        } else if (jRadioButton2.isSelected()){
            h1 = (ti - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        
        if (h1 < bt) {
            kideal.setText(temp);
            hasil.setText("Maaf " + knama.getText() + " , Sepertinya anda Overweight :( ");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        } else if (h1 > bt) {
            kideal.setText(temp);
            hasil.setText("Maaf " + knama.getText() + " , Sepertinya anda Underweight :(");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        } else {
            kideal.setText(temp);
            hasil.setText("Hallo " + knama.getText() + " , Berat badan anda sudah ideal :)");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
        }
        
    }
}
